The_GST_1/Controllers/QueryController.cs
using Microsoft.AspNetCore.Mvc;
using Repository_Logic.Dto;
using Repository_Logic.ErrorLogsRepository.Interface;
using Repository_Logic.QueryRepository.Interface;
using Repository_Logic.TaskAllocation.Implementation;
using System.Security.Claims;

namespace The_GST_1.Controllers
{
    public class QueryController : Controller
    {
        private readonly IQuery _query;

        private readonly IErrorLogs _errorLogs;
        public QueryController(IQuery query, IErrorLogs errorLogs)
        {
            _query = query;
            _errorLogs = errorLogs;
        }

        public async Task<IActionResult> QueryListForUser()// List of the Queries submitted by user for user side dashboard.
        {
            try
            {
                
                var LoginSessionID = "null";

                if (User.Identity.IsAuthenticated)
                {
                    LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                }

                List<Query_Dto> queries = await _query.GetAllQueries(LoginSessionID);
                return View(queries);
            }
            catch (Exception ex)
            {
                ErrorLog_Dto errorLog_Dto = new ErrorLog_Dto();

                errorLog_Dto.Date = DateTime.Now;
                errorLog_Dto.Message = ex.Message;
                errorLog_Dto.StackTrace = ex.StackTrace;

                _errorLogs.InsertErrorLog(errorLog_Dto);
                var errorMessage = "AN ERROR OCCURRED WHILE LOADING QUERIES.";
                return RedirectToAction("ErrorHandling", "Home", new { ErrorMessage = errorMessage });
            }

        }

        public async Task<JsonResult> QueryListForUserDatatable()// Datatable for list of the queries provided by user for user side dashboard.
        {
            var LoginSessionID = "null";
            var dataTable_ = new DataTable_Dto
            {
                Draw = Request.Form["draw"].FirstOrDefault(),
                sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(),
                sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault(),
                SearchValue = Request.Form["search[value]"].FirstOrDefault(),
                PageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0"),
                Skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0")
            };

            if (User.Identity.IsAuthenticated)
            {
                LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            }

            List<Query_Dto> Records = await _query.QueryListForUserDatatable(dataTable_, LoginSessionID);
            var totalRecord = Records.Count();
            var filterRecord = Records.Count();
            var FellowshipList = Records.Skip(dataTable_.Skip).Take(dataTable_.PageSize).ToList();
            var returnObj = new
            {
                draw = dataTable_.Draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = FellowshipList
            };
            return Json(returnObj);

        }



        public IActionResult InsertQuestion(string query)// Question inserted by the user (User side dashboard).
        {
            try
            {
               
                var LoginSessionID = "null";

                if (User.Identity.IsAuthenticated)
                {
                    LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                }
                Query_Dto query_Dto = new Query_Dto();
                query_Dto.Question = query;
                query_Dto.UserID = LoginSessionID;
                query_Dto.QuestionAskedDate = DateTime.Now;
                _query.insert(query_Dto);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                ErrorLog_Dto errorLog_Dto = new ErrorLog_Dto();

                errorLog_Dto.Date = DateTime.Now;
                errorLog_Dto.Message = ex.Message;
                errorLog_Dto.StackTrace = ex.StackTrace;

                _errorLogs.InsertErrorLog(errorLog_Dto);
                TempData["ErrorMessage"] = "AN ERROR OCCURRED WHILE SUBMITTING THE QUERY. ";

                return Json(new { success = false, message = TempData["ErrorMessage"] });
            }

        }

        public async Task<IActionResult> QueryListForCADashboard() // list of the queries at CA dashboard.
        {
            try
            {
               
                var LoginSessionID = "null";

                if (User.Identity.IsAuthenticated)
                {
                    LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                }
                List<Query_Dto> queries = await _query.GetAllQueries(LoginSessionID);
                return View(queries);
            }
            catch (Exception ex)
            {
                ErrorLog_Dto errorLog_Dto = new ErrorLog_Dto();

                errorLog_Dto.Date = DateTime.Now;
                errorLog_Dto.Message = ex.Message;
                errorLog_Dto.StackTrace = ex.StackTrace;

                _errorLogs.InsertErrorLog(errorLog_Dto);
                var errorMessage = "AN ERROR OCCURRED WHILE LOADING QUERIES.";
                return RedirectToAction("ErrorHandling", "Home", new { ErrorMessage = errorMessage });

            }
        }


        public async Task<JsonResult> QueryListForCADatatable() //Datatable for list of queries (CA Dashboard)
        {
            var LoginSessionID = "null";
            var dataTable_ = new DataTable_Dto
            {
                Draw = Request.Form["draw"].FirstOrDefault(),
                sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(),
                sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault(),
                SearchValue = Request.Form["search[value]"].FirstOrDefault(),
                PageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0"),
                Skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0")
            };

            if (User.Identity.IsAuthenticated)
            {
                LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            }

            List<Query_Dto> Records = await _query.QueryListForCADatatable(dataTable_, LoginSessionID);
            var totalRecord = Records.Count();
            var filterRecord = Records.Count();
            var FellowshipList = Records.Skip(dataTable_.Skip).Take(dataTable_.PageSize).ToList();
            var returnObj = new
            {
                draw = dataTable_.Draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = FellowshipList
            };
            return Json(returnObj);

        }


        public IActionResult InsertAnswerToQuestion(Query_Dto query_Dto) // Inserting Answer to question (CA Dashboard)
        {

            try
            {
                

                var LoginSessionID = "null";

                if (User.Identity.IsAuthenticated)
                {
                    LoginSessionID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                }

                _query.InsertAnswerToQuestion(query_Dto, LoginSessionID);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                ErrorLog_Dto errorLog_Dto = new ErrorLog_Dto();

                errorLog_Dto.Date = DateTime.Now;
                errorLog_Dto.Message = ex.Message;
                errorLog_Dto.StackTrace = ex.StackTrace;

                _errorLogs.InsertErrorLog(errorLog_Dto);
                var errorMessage = "AN ERROR OCCURRED WHILE SUBMITTING THE ANSWER.";
                return Json(new { success = false, message = errorMessage });

            }

        }




    }
}

The_GST_1/Views/Query/QueryListForCADashboard.cshtml
@model IEnumerable<Repository_Logic.Dto.Query_Dto>




<div class="card shadow mb-4" style="border-radius:15px; box-shadow: 0 5px 10px rgba(0,0,0,0.1);">
    <span id="TextBoxValidation" class="alert" style="display:none;color:white;background-color:red;scroll-margin:inherit;margin-left:80%;"></span>
    <div class="card-header py-3" style="background-color:#002F6C;border-top-right-radius: 15px;border-top-left-radius: 15px">
        <h1 class="Nameheader"><b>Query List</b></h1>
    </div>
    <div class="card-body ">
        <br />
        <div class="table-responsive">
            <table class="table table-bordered" id="QueryListForCADataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            UserName
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Query
                        </th>
                        <th>
                            Question Asked Date
                        </th>
                        <th>
                            Answered Question Date
                        </th>
                        <th>
                            Answer
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem=>item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Question)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.QuestionDate)
                            </td>
                            <td>
                                @if (item.Answer == "Not Yet Answered")
                                {
                                    <p>Not Answered By CA</p>
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => item.AnswerDate)
                                }
                            </td>
                            <td>
                                @if (item.Answer == "Not Yet Answered")
                                {
                                    <form method="post" asp-controller="Query" asp-action="Insert" enctype="multipart/form-data" onsubmit="showConfirmation(this, event)">
                                        <div class="form-group">
                                            <input type="hidden" name="Id" value="@item.Id" />
                                            <textarea name="Answer" id="AnswerTextBox1" style="width:400px;" placeholder="Enter The Answer"></textarea>
                                            <button type="submit" class="btn btn-primary" id="submitButton">
                                                <span>Submit</span>

                                            </button>
                                        </div>
                                    </form>

                                }
                                else
                                {

                                    @Html.DisplayFor(modelItem => item.Answer)
                                }
                            </td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

</span>
@section Scripts
    {

    <script>
        let btn = document.getElementById("submitButton");;



        function showConfirmation(form, event) {
            event.preventDefault();
            var rowId = form.elements["Id"].value;
            var Answer = document.getElementById('AnswerTextBox1' + rowId).value;
            // var validationSpan = $('#TextBoxValidation');

            // console.log(rowId);
            var validationMessage = document.getElementById('Validation' + rowId);
            console.log("Answer: " + Answer);
            if (!Answer) {
                validationMessage.textContent = "Answer is required.";

                // validationSpan.text("Answer is required.").fadeIn().delay(2000).fadeOut("slow");
                // Show the validation alert
            } else {

                validationMessage.textContent = "";
                document.getElementById("TextBoxValidation").textContent = "";
                Swal.fire({
                    title: 'Do you want to submit the Answer?',
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonText: 'OK',
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: "/Query/InsertAnswerToQuestion",
                            type: "POST",
                            data: $(form).serialize(),
                            success: function (response) {
                                if (response.success) {
                                    console.log(response);
                                    console.log(response.success);
                                    Swal.fire({
                                        title: 'Success!',
                                        text: 'Answer Submitted successfully.',
                                        icon: 'success',
                                        confirmButtonText: 'OK'
                                    })


                                    location.reload(true);
                                }
                                else {
                                    console.log(response.message)
                                    window.location.href = '/Home/ErrorHandling?ErrorMessage=' + encodeURIComponent(response.message);;
                                
                                }

                            },
                            error: function (request, status, error) {
                                Swal.fire({
                                    title: 'Error!',
                                    text: 'An error occurred while processing your request.',
                                    icon: 'error',
                                    confirmButtonText: 'OK'
                                });
                            }
                        });
                    }
                });
            }
            return false;
        }


        $(document).ready(function () {

            if ($.fn.DataTable.isDataTable('#QueryListForCADataTable')) {
                $('#QueryListForCADataTable').DataTable().destroy();
            }

            $('#QueryListForCADataTable').DataTable(
                {
                    "processing": true,
                    "serverSide": true,
                    "filter": true,
                    "ajax": {
                        "url": "/Query/QueryListForCADatatable",
                        "type": "POST",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "userName", "name": "UserName" },
                        { "data": "email", "name": "Email" },
                        {
                            "data": "question", "name": "Question"
                        },
                        { "data": "questionDate", "name": "QuestionDate" },
                        {
                            "data": "answerDate", "name": "AnswerDate",
                            "render": function (data, type, row) {
                                if (row.answer == "Not Yet Answered") {
                                    // Render explicit answer based on the condition
                                    return "Not Answered By CA";
                                } else {
                                    // Render the regular answer
                                    return data;
                                }
                            }

                        },
                        {
                            "data": "answer", "name": "Answer",

                            "render": function (data, type, row) {
                                if (row.answer == "Not Yet Answered") {

                                    return '<td>' + '<form method="post" asp-controller="Query" asp-action="Insert" enctype="multipart/form-data" onsubmit="showConfirmation(this, event)">' +
                                        '<div class="row" >' +
                                        '<div class="col-md-8">' +
                                        '<div class="form-group">' +
                                        '<input type="hidden" name="Id" value="' + row.id + '" />' +
                                        '<textarea name="Answer" id="AnswerTextBox1' + row.id + '" style="width:400px;" placeholder="Enter The Answer"></textarea>' +
                                        '<span id="Validation' + row.id + '" class="text-danger"></span>' +
                                        '</div>' +
                                        '</div>' +
                                        '<div class="col-md-4">' +
                                        '<div class="form-group">' +
                                        '<button type="submit" class="btn btn-primary" style="margin-top:10px;margin-left:120px" id="submitButton">' +
                                        'Submit' +
                                        '</button>' +
                                        '</div>' +
                                        '</div>' +
                                        '</div>' +
                                        '</form>' + '</td>';

                                    // Render explicit answer based on the condition
                                } else {
                                    // Render the regular answer
                                    return data;
                                }
                            }


                        }
                    ]
                }
            );

        });




    </script>
}

The_GST_1/Views/Query/QueryListForUser.cshtml
@model IEnumerable<Repository_Logic.Dto.Query_Dto>



<br/>
<div class="card shadow mb-4" style="border-radius:15px; box-shadow: 0 5px 10px rgba(0,0,0,0.1);">
    <div class="card-header py-3" style="background-color:#002F6C;border-top-right-radius: 15px;border-top-left-radius: 15px">
        <h1 class="Nameheader"><b>Please Enter your questions</b></h1>
    </div>
    <div class="card-body ">
        
        <form method="post" asp-controller="Query" asp-action="InsertQuestion" enctype="multipart/form-data" onsubmit="showConfirmation(this)">
            <br />
            <div class="row" class="form-group">            
                <textarea name="query" id="QueryTextBox" style="width:1100px;" class="form-control" placeholder="Enter The Query"></textarea>
                 <div style="font-size:10px;"> <br /> 
                 <button type="submit" class="btn btn-primary"  style="margin-left:10px;width:140px;" id="submitButton">Submit</button> </div>
            </div>
            <span id="QueryTextBoxValidation" class="text-danger" style="margin-left:10px;"></span>
        </form>
    </div>
 </div>
    <br />
<div class="card shadow mb-4">
    <div class="card-header py-3" style="background-color:#002F6C">
        <h1 class="Nameheader"><b>Queries</b></h1>
    </div>
    <div class="card-body ">
        <div class="table-responsive">
            <table  id="QueryListForUserDataTable" class="table table-bordered"  width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                           Queries
                        </th>
                        <th>
                            Answer
                        </th>
                        <th>
                            Answered By
                        </th>
                        <th>
                           Question Asked Date
                        </th>
                        <th>
                           Answered Question Date
                        </th>   
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Question)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem=>item.Answer)
                            </td>
                            <td>
                             
                                @Html.DisplayFor(modelItem => item.AnsweredBy)
                             
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.QuestionDate)
                            </td>
                            <td>
                                @if (item.Answer == "Not Yet Answered")
                                {
                                  <p>Not Answered By CA</p>
                                }
                                else
                                {
                                @Html.DisplayFor(modelItem => item.AnswerDate)
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>





@section Scripts
    {

 <script>

  function showConfirmation(form) {
      event.preventDefault();
      var Remark = $('#QueryTextBox').val();
      if (!Remark) {
          if (!Remark) {
              document.getElementById("QueryTextBoxValidation").textContent = "Query is required.";
          } else {
              document.getElementById("QueryTextBoxValidation").textContent = "";
          }

      }
      else {
          Swal.fire({
              title: 'Do you want to submit the Query?',
              icon: 'info',
              showCancelButton: true,
              confirmButtonText: 'OK',
          }).then((result) => {
              if (result.isConfirmed) {
                  $.ajax({
                      url: "/Query/InsertQuestion",
                      type: "POST",
                      data: $(form).serialize(),
                      success: function (response) {
                          if (response.success) {
                              console.log(response);
                              console.log(response.success);
                              Swal.fire({
                                  title: 'Success!',
                                  text: 'Query Submitted successfully.',
                                  icon: 'Success',
                                  confirmButtonText: 'OK'
                              })
                              location.reload(true);
                          }
                          else {

                                    console.log(response.message)
                                    window.location.href = '/Home/ErrorHandling?ErrorMessage=' + encodeURIComponent(response.message);;
                          }
                      },
                      error: function (request, status, error) {
                          Swal.fire({
                              title: 'Error!',
                              text: 'An error occurred while processing your request.',
                              icon: 'error',
                              confirmButtonText: 'OK'
                          });       
                      }
                  });
              }
              else {
              }
          });
          return false;
      }
    }


        // $(document).ready(function () {

        //     if ($.fn.DataTable.isDataTable('#QueryListForUserDataTable')) {
        //         $('#QueryListForUserDataTable').DataTable().destroy();
        //     }

        //     $('#QueryListForUserDataTable').DataTable(
        //         {
        //             "processing": true,
        //             "serverSide": true,
        //             "filter": true,
        //             "ajax": {
        //                 "url": "/Query/QueryListForUserDatatable",
        //                 "type": "POST",
        //                 "datatype": "json" 
                       
        //             },
        //             "order": [
        //                 { "column": 3, "order": "desc" }
        //             ],
        //             "columns": [
        //                 { "data": "question", "name": "Question" },
        //                 { "data": "answer", "name": "Answer" },
        //                 { "data": "answeredBy", "name": "AnsweredBy",

        //                      "render": function (data, type, row) {
        //                         if (row.answer == "Not Yet Answered") {
        //                             // Render explicit answer based on the condition
        //                             return "Not Answered By CA";
        //                         } else {
        //                             // Render the regular answer
        //                             return data;
        //                         }
        //                     }                      
        //                 },
        //                 { "data": "questionDate", "name": "QuestionDate" },
        //                 { "data": "answerDate", "name": "AnswerDate" ,

        //                     "render": function (data, type, row) {
        //                         if (row.answer == "Not Yet Answered") {
        //                             // Render explicit answer based on the condition
        //                             return "Not Answered By CA";
        //                         } else {
        //                             // Render the regular answer
        //                             return data;
        //                         }
        //                     }

        //                 }
        //             ]
        //         }
        //     );

        // });


        $(document).ready(function () {

            if ($.fn.DataTable.isDataTable('#QueryListForUserDataTable')) {
                $('#QueryListForUserDataTable').DataTable().destroy();
            }

            $('#QueryListForUserDataTable').DataTable(
                {
                    "processing": true,
                    "serverSide": true,
                    "order": [4, 'asc'],
                    "filter": true,
                    "ajax": {
                        "url": "/Query/QueryListForUserDatatable",
                        "type": "POST",
                        "datatype": "json"
                    },         
                  
                     "columns": [
                        { "data": "question", "name": "Question" },
                        { "data": "answer", "name": "Answer" },
                        {
                            "data": "answeredBy", "name": "AnsweredBy",

                            "render": function (data, type, row) {
                                if (row.answer == "Not Yet Answered") {
                                    // Render explicit answer based on the condition
                                    return "Not Answered By CA";
                                } else {
                                    // Render the regular answer
                                    return data;
                                }
                            }
                        },
                        { "data": "questionDate", "name": "QuestionDate" },
                        {
                            "data": "answerDate", "name": "AnswerDate",

                            "render": function (data, type, row) {
                                if (row.answer == "Not Yet Answered") {
                                    // Render explicit answer based on the condition
                                    return "Not Answered By CA";
                                } else {
                                    // Render the regular answer
                                    return data;
                                }
                            }

                        }
                    ]                
                }
            );

        });



</script>
}